### ISSUE TITLE
Peer to peer code review 

### ISSUE THREAD

**Issue by sajid-munawar** [Roseokpe/First-capstone-Project#2]
- Your program section is very impressive.
-  There are some things that I notice in other sections that can be improved which are:
- In your README file please add a link in this way [live demo](https://roseokpe.github.io/First-capstone-Project/)
- Please give some padding and margin to your hero content.
- Please keep the same size for all speaker images (also if you can add chess background)
- When the user clicks on the hamburger icon the menu bar should appear and background content should disappear.

**Comment by MicroverseNelson** [comment]
##Campstone 
- Great Job with following a good coding convention
- Try to follow the figma design. 
- Work on your spacing, margins top bottom, right and left
- Overall, Good job
